### ISSUE TITLE
Missing master_pokemon_info.txt

### ISSUE THREAD

**Issue by NoelDavies** [EverOddish/Westwood#22]
Just curious if I'm missing something? 

In https://github.com/EverOddish/Westwood/blob/master/import/scripts/bdsp/parse_master_info.py#L525, it references a file that doesn't exist in the repo?

So there's not much context about formats minus those regular expressions, etc.

**Comment by NoelDavies** [comment]
Also @EverOddish you might want to remove line 613 ;)

**Comment by EverOddish** [comment]
Sorry, just saw this now. I added the data file and fixed the other thing. Thanks for pointing that out!
